version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "05:00"
      timezone: "Asia/Calcutta"
    labels:
      - "CI/CD"
    commit-message:
      prefix: ci
